### ISSUE TITLE
复现的结果与论文中的不一致，请问需要调整哪些参数？

### ISSUE THREAD

**Issue by Allan-waker** [NLPWM-WHU/SLGM#2]
这是在rest15测试集上的结果(66.5)，和论文中的结果(68.2)差了1.7个点，请问这是正常的吗？需要调整哪些参数？或者可以提供你代码中的参数吗？谢谢！
![屏幕截图 2024-04-09 164122](https://github.com/NLPWM-WHU/SLGM/assets/64625837/32ea06ca-9b01-44a2-9eb6-fb0af3192ab3)
![image](https://github.com/NLPWM-WHU/SLGM/assets/64625837/903281e5-5671-4368-8015-daa913defbd4)

**Comment by ZHOUSHEN713** [comment]
您好， 我刚刚重新跑了一次代码，环境和 #1 中的一致，只要将scripts/run_single.sh中的dataset设置为rest15即可，参数保持一致，下面是我刚刚运行的结果：
<img width="769" alt="image" src="https://github.com/NLPWM-WHU/SLGM/assets/49969011/d834de04-66b1-4ac2-b069-51876f06b53f">
