### ISSUE TITLE
请问训练过程是保存在验证集上效果最好的模型权重吗？

### ISSUE THREAD

**Issue by Allan-waker** [NLPWM-WHU/SLGM#3]
这里加载的pytorch_model.bin文件是从哪里来的？
![image](https://github.com/NLPWM-WHU/SLGM/assets/64625837/641efd83-ba1d-4f64-aa89-e017a0ed2c8c)

**Comment by ZHOUSHEN713** [comment]
您好，很抱歉我没有收到提醒邮件所以回复可能经常比较慢。

Q：请问训练过程是保存在验证集上效果最好的模型权重吗？
A：我们跟先前的工作GAS[https://github.com/IsakZhang/Generative-ABSA/blob/main/main.py](url)保持一致，都是直接训练20个epoch然后直接进行验证的，没有使用验证集，所以在参数上跟先前的工作都是保持一致。

Q：这里加载的pytorch_model.bin文件是从哪里来的？
A：这是模型训练完保留的权重，后面要测试的话直接加载就好了，不用再次训练。

**Comment by Allan-waker** [comment]
> 您好，很抱歉我没有收到提醒邮件所以回复可能经常比较慢。
> 
> Q：请问训练过程是保存在验证集上效果最好的模型权重吗？ A：我们跟先前的工作GAS[https://github.com/IsakZhang/Generative-ABSA/blob/main/main.py](url)保持一致，都是直接训练20个epoch然后直接进行验证的，没有使用验证集，所以在参数上跟先前的工作都是保持一致。
> 
> Q：这里加载的pytorch_model.bin文件是从哪里来的？ A：这是模型训练完保留的权重，后面要测试的话直接加载就好了，不用再次训练。

好的，谢谢你的解答！
