### ISSUE TITLE
代码在不同的随机种子下结果差异大的问题

### ISSUE THREAD

**Issue by Allan-waker** [NLPWM-WHU/SLGM#4]
你好，我使用你提供的代码，发现在其他参数不变的情况下，选取不同的seed，结果差别较大，有时候结果能相差2个点，请问这是正常的现象吗？还有你论文中的实验结果是对不同seed运行后的结果取平均吗？还是某一个seed的实验结果？谢谢！

**Comment by NLPWM-WHU** [comment]
你好，全量数据的场景下取5次随机种子平均的结果，低资源场景下取10次随机种子平均的结果。
